# Generated by Django 5.2.7 on 2025-11-15 13:14

import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_handler_alter_customuser_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
