# Generated by Django 5.2.7 on 2025-10-18 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="name",
            new_name="title",
        ),
    ]
