# Generated by Django 5.2.7 on 2025-10-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_rename_name_recipe_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="abbreviation",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="unit",
            name="name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
