# Generated by Django 5.2.7 on 2025-10-24 11:34

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0004_alter_unit_abbreviation_alter_unit_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="instructions",
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid6.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step", models.IntegerField()),
                ("description", models.TextField()),
                ("timer", models.IntegerField(blank=True, null=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="kitchen.recipe",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
