# Generated by Django 5.2.7 on 2025-10-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0005_remove_recipe_instructions_instruction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="image",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
