# Generated by Django 5.2.7 on 2025-10-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_alter_ingredient_image_alter_recipe_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("FRIENDS", "Friends"),
                    ("PRIVATE", "Private"),
                ],
                default="PRIVATE",
                max_length=10,
            ),
        ),
    ]
