# Generated by Django 5.2.7 on 2025-11-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0007_recipe_visibility"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instruction",
            options={"ordering": ["step"]},
        ),
    ]
