# Generated by Django 5.2.7 on 2025-11-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0008_alter_instruction_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
