# Generated by Django 5.2.7 on 2025-11-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0009_recipe_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
