# Generated by Django 5.2.7 on 2025-11-02 09:21

from django.db import migrations


def mark_existing_recipes_as_finished(apps, schema_editor):
    Recipe = apps.get_model("kitchen", "Recipe")
    Recipe.objects.all().update(is_draft=False)


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0010_recipe_slug_alter_recipe_title"),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_recipes_as_finished, migrations.RunPython.noop
        ),
    ]
