# Generated by Django 5.2.7 on 2025-11-04 14:56

from django.db import migrations, models
from nanoid import generate
from slugify import slugify


def slugify_titles(apps, schema_editor):
    Recipe = apps.get_model("kitchen", "Recipe")
    db_alias = schema_editor.connection.alias

    recipes_to_update = Recipe.objects.using(db_alias).filter(
        models.Q(slug__isnull=True) | models.Q(slug=""), title__isnull=False
    )

    recipes = []
    for recipe in recipes_to_update:
        slug = slugify(recipe.title)

        while Recipe.objects.using(db_alias).filter(slug=slug).exists():
            slug = f"{slugify(recipe.title)}-{generate(size=4)}"

        recipe.slug = slug
        recipes.append(recipe)

    Recipe.objects.using(db_alias).bulk_update(recipes, ["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("kitchen", "0011_mark_existing_resipes_as_finished"),
    ]

    operations = [migrations.RunPython(slugify_titles, migrations.RunPython.noop)]
