# Generated by Django 5.2.7 on 2025-11-15 13:14

import shared.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0013_appliancetype_manufacturer_appliance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appliance",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="appliancetype",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="recipeingredient",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="uid",
            field=models.UUIDField(
                db_default=shared.models.UUIDv7(),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
