# Generated by Django 5.2.7 on 2026-01-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0014_alter_appliance_uid_alter_appliancetype_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="appliances",
            field=models.ManyToManyField(to="kitchen.appliance"),
        ),
    ]
